logging:
  config: classpath:logConfig.xml
spring:
  datasource:
    url: jdbc:mysql://{连接地址}:{端口}/{库名}?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://{账号}:{密码}@{连接地址}:{端口}/{库名}?authMechanism=SCRAM-SHA-1&socketTimeoutMS=3000&maxIdleTimeMS=180000
  profiles:
    active: prod
wejuai-core:
  url: http://core-svc:8080 #wejuai-core内网连接地址
trade-gateway:
  url: http://trade-gateway-svc:8080 #wejuai-trade-gateway内网连接地址
aliyun:
  nms:
    endpoint: http://{nmsId}.mns.cn-beijing-internal.aliyuncs.com/