spring:
  datasource:
    url: jdbc:mysql://{连接地址}:{端口}/{库名}?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://{账号}:{密码}@{连接地址}:{端口}/{库名}?authMechanism=SCRAM-SHA-1&socketTimeoutMS=3000&maxIdleTimeMS=180000
  jpa:
    show-sql: true
  profiles:
    active: dev
logging:
  level:
    com.wejuai: debug
    com.endofmaster: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
wejuai-core:
  url: http://127.0.0.1:8085
trade-gateway:
  url: http://127.0.0.1:8084