server:
  port: 8080
spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    username: xxxxxx
    password: xxxxxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 300000
      pool-name: wejuaiPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  data:
    mongodb:
      uri: mongodb://{账号}:{密码}@{连接地址}:{端口}/{库名}?authMechanism=SCRAM-SHA-1&socketTimeoutMS=3000&maxIdleTimeMS=180000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
qq: #qq开放登录平台
  app-id: xxxxxx
  app-key: xxxxxx
  redirect-url: https://accounts.wejuai.com/accounts/authorize/qq
weibo: #微博公众平台
  app-id: xxxxxx
  app-key: xxxxxx
  redirect-url: https://accounts.wejuai.com/accounts/authorize/weibo
tx-ai: #腾讯开放平台
  app-id: xxxxxx
  app-key: xxxxxx
weixin:
  offi-origin-id: xxxxxxx #公众号原始id
  app-origin-id: xxxxxxx #小程序原始id
  open-id: xxxxxxx #开放平台 accessKey
  open-secret: xxxxxx #开放平台 accessSecret
  offi-id: xxxxxx #公众号 accessKey
  offi-secret: xxxxxx #公众号 accessSecret
  app-id: xxxxxx #小程序accessKey
  app-secret: xxxxxx #小程序 accessSecret
  redirect-url: https://accounts.wejuai.com/accounts/authorize/wx
  gateway: http://weixin-gateway-svc:8080 #这是k8s内部网络地址，实际上是微信gateway服务地址
  msg:
    app-audit: xxxxxx #审核通知模版消息id
    app-reply: xxxxxx #应用收到回复的模版消息id
    app-reward-demand-selected: xxxxxx #悬赏回到被选中的模版消息id
    app-reward-demand-expire: xxxxxx #悬赏到期提醒模版id
  page: #小程序对应页面，发送模版消息使用
    article: "/essay/pages/info/index" #文章
    reward: "/group/pages/info/index" #悬赏
    orders: "/integral/pages/detailInfo/index" #订单
    withdrawal: "/integral/pages/detailInfo/index" #提现
aliyun:
  accessKeyId: xxxxxx
  accessKeySecret: xxxxxx
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: xxxxxx
    imageCallbackUrl: https://accounts.wejuai.com/images/callback #三种类型的前端直传oss回调地址
    videoCallbackUrl: https://accounts.wejuai.com/videos/callback
    audioCallbackUrl: https://accounts.wejuai.com/audios/callback
  mns:
    name: charge-started
    endpoint: https://{mnsId}.mns.cn-beijing.aliyuncs.com/
health:
  config:
    enabled: false